version: '3'

services:
  postgres:
    image: postgres

    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qsbm
    volumes:
    - data01:/var/lib/postgresql/data
volumes:
  data01:
    driver: local